# Generated by Django 3.1.7 on 2021-10-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myftsapp', '0002_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Name',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Experience',
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
